# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
  - name: succeed
    displayName: Succeed or Fail
    type: boolean
    default: false
trigger:
- main

pool:
  default

jobs:
- job: Work
  steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
      curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
    displayName: 'Installing Az CLI'


  - script: git clone malformed input
    condition: eq(${{ parameters.succeed }}, false)

- job: ErrorHandler
  dependsOn: Work
  condition: failed()
  steps: 
  - bash: |
      az boards work-item create \
      --title "Build $(build.buildNumber) failed" \
      --type bug \
      --org $(System.TeamFoundationCollectionUri) \
      --project $(System.TeamProject)
    env: 
      AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
    displayName: 'Create work item on failure'
